repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  # for list of all available hooks in pre-commit repo, see: https://pre-commit.com/hooks.html
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
    - id: black
      args: [--line-length=120]
      language_version: python3.10
- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
    - id: flake8
      # Ignore formatting errors (E,W), since they are handled by black
      args: [--ignore=E,W]
      additional_dependencies: [flake8-typing-imports==1.12.0]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.931
  hooks:
    - id: mypy
      args: [--disallow-untyped-defs, --disallow-incomplete-defs, --ignore-missing-imports]
      additional_dependencies: [types-all]
- repo: https://github.com/myint/docformatter
  rev: v1.3.1
  hooks:
    - id: docformatter
      args: [--in-place, --wrap-summaries=120, --wrap-descriptions=120, --pre-summary-newline]
